# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fddc46c7db762b01c4bf70e5fbca28b7cdce265c634c13eada0faa40d80f92a4c0709ce460e76c910640786bc99b4445f956d65fc17bcd9bdcef572c3979975

test:
  secret_key_base: a65668d963020bcf71ff5cc8e0c8a128188c06967a3f7f053e5b98495b381b970f27368f621ab2594733aecce94e56eac15858c765b9baa5ab7265abc7932bfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
